import { createServer } from 'node:http'
import { readFile, stat, mkdir } from 'node:fs/promises'
import { resolve, extname } from 'node:path'
import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'

const root = resolve('dist')
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.webp': 'image/webp' }
const server = createServer(async (req, res) => {
  try {
    let file = resolve(root, '.' + decodeURIComponent(new URL(req.url, 'http://localhost').pathname))
    if (!file.startsWith(root)) { res.writeHead(403); return res.end() }
    try { if (!(await stat(file)).isFile()) file = resolve(root, 'index.html') } catch { file = resolve(root, 'index.html') }
    res.setHeader('Content-Type', types[extname(file)] || 'application/octet-stream')
    res.end(await readFile(file))
  } catch { res.writeHead(500); res.end('Read error') }
})
await new Promise(resolve => server.listen(4179, '127.0.0.1', resolve))
await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
const errors = []
page.on('pageerror', error => errors.push(error.message))
try {
  await page.goto('http://127.0.0.1:4179', { waitUntil: 'networkidle' })
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'artifacts/desktop-light.png', fullPage: true })
  await expect(page.locator('.place-card')).toHaveCount(3)
  assert.equal(await page.title(), 'Assiette — Good food. Small budget.')
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
  await page.screenshot({ path: 'artifacts/desktop-dark.png', fullPage: true })
  await page.reload({ waitUntil: 'networkidle' })
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  await page.getByRole('searchbox').fill('Bullier')
  await expect(page.locator('.place-card')).toHaveCount(1)
  assert.match(await page.locator('.place-name').innerText(), /Bullier/)
  await page.getByRole('searchbox').fill('no-such-place')
  await page.getByRole('heading', { name: 'Nothing on this plate yet.' }).waitFor()
  await page.locator('.empty-state').getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.getByRole('button', { name: 'Food distributions 2', exact: true }).click()
  await expect(page.locator('.place-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'All options 4', exact: true }).click()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByLabel('Free options', { exact: true }).check()
  await page.getByRole('button', { name: 'Show results (2)' }).click()
  await expect(page.locator('.place-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'Filters 1' }).click()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Save place: CROUS Mabillon', exact: true }).click()
  await page.locator('.desktop-nav').getByRole('link', { name: 'Saved places 1' }).click()
  await page.waitForURL('**/saved')
  await expect(page.locator('.place-card')).toHaveCount(1)
  await page.locator('.place-name').click()
  await page.getByRole('dialog', { name: 'CROUS Mabillon' }).waitFor()
  assert.ok(await page.getByRole('link', { name: 'Visit the official source' }).getAttribute('href'))
  await page.screenshot({ path: 'artifacts/detail.png' })
  await page.keyboard.press('Escape')
  await page.locator('.desktop-nav').getByRole('link', { name: 'Find a meal', exact: true }).click()
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await page.locator('.leaflet-container').waitFor()
  await expect(page.locator('.custom-map-marker')).toHaveCount(2)
  await page.screenshot({ path: 'artifacts/map.png', fullPage: true })
  await page.getByRole('button', { name: 'Switch to French' }).click()
  await page.getByRole('heading', { name: /Bien manger.*Petit budget/ }).waitFor()
  assert.equal(await page.locator('html').getAttribute('lang'), 'fr')
  await page.getByRole('button', { name: 'Passer en anglais' }).click()
  await page.locator('.desktop-nav').getByRole('link', { name: 'How it works' }).click()
  await page.getByRole('heading', { name: 'A better-fed student life.' }).waitFor()
  await page.screenshot({ path: 'artifacts/about.png', fullPage: true })
  await page.getByRole('link', { name: 'Sign in', exact: true }).click()
  await page.getByLabel('What should we call you?').fill('Camille')
  await page.getByRole('button', { name: 'Create my local profile' }).click()
  await page.waitForURL('**/saved')
  assert.equal(await page.locator('.signin-link').innerText(), 'Camille')
  await page.reload({ waitUntil: 'networkidle' })
  await expect(page.locator('.place-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Privacy & your data' }).click()
  await page.getByRole('button', { name: 'Clear my saved data' }).click()
  await expect(page.locator('.place-card')).toHaveCount(0)
  await page.goto('http://127.0.0.1:4179')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'artifacts/mobile-light.png', fullPage: true })
  const overflow = await page.evaluate(() => [...document.querySelectorAll('body *')].filter(el => el.getBoundingClientRect().right > window.innerWidth + 1 && getComputedStyle(el).position !== 'fixed').map(el => `${el.tagName}.${el.className}: ${el.getBoundingClientRect().right}`).slice(0, 12))
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile page overflows horizontally: ' + overflow.join(', '))
  await page.getByRole('button', { name: 'Toggle navigation' }).click()
  await page.locator('.mobile-nav').getByRole('link', { name: 'How it works' }).click()
  await page.getByRole('heading', { name: 'A better-fed student life.' }).waitFor()
  await page.waitForTimeout(100)
  assert.equal(await page.locator('.mobile-nav').count(), 0)
  await page.locator('.site-header .brand').click()
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await page.screenshot({ path: 'artifacts/mobile-dark.png', fullPage: true })
  assert.equal(errors.length, 0, errors.join('\n'))
  console.log('PASS: light/dark persistence, search, empty state, categories, price filters, bookmarks, details, map, EN/FR, about, local profile, privacy, mobile navigation, responsive overflow, and zero browser errors.')
} finally {
  await browser.close()
  await new Promise(resolve => server.close(resolve))
}
